version: '3.8'

services:

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - database_volume:/var/lib/postgresql/data/
    env_file:
      - ./backend/.dbenv
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres


  backend:
    container_name: backend
    build: ./backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      database:
        condition: "service_healthy"
    env_file:
      - ./backend/.dev_env


  frontend:
    build:
      context: ./frontend
      args:
        - VUE_APP_BASE
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: vue-ui


volumes:
  database_volume:
