version: '3.8'
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - database_volume:/var/lib/postgresql/data/
    environment:
      DATABASE_HOSTNAME: "postgres"
      POSTGRES_DB: "xakaton"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    env_file:
      - .dbenv
      - .dev_env
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres

  backend:
    container_name: backend
    build: .
    command: bash -c "alembic upgrade head && python3.11 dbinit.py  && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      database:
        condition: "service_healthy"
    env_file:
      - .dbenv
      - .dev_env
    environment:
      PYTHONPATH: "/xakaton/backend/"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - VUE_APP_BASE

    ports:
      - "8080:80"

volumes:
  database_volume: