"""initial

Revision ID: 10af0a30e018
Revises: 
Create Date: 2023-05-27 23:06:12.765499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10af0a30e018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
