"""reworked models and schemas

Revision ID: 728bd8223be1
Revises: 74b2d9861baf
Create Date: 2023-05-25 00:00:17.369541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728bd8223be1'
down_revision = '74b2d9861baf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('excursion', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('hotel', sa.Column('stars', sa.String(), nullable=True))
    op.add_column('hotel', sa.Column('list_services', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'list_services')
    op.drop_column('hotel', 'stars')
    op.drop_column('excursion', 'duration')
    op.drop_column('event', 'duration')
    # ### end Alembic commands ###
