"""initial

Revision ID: e14b083f4909
Revises: 1ed718c6efab
Create Date: 2023-05-28 17:20:04.128654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14b083f4909'
down_revision = '1ed718c6efab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mldata', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('mldata', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mldata', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mldata', 'username')
    # ### end Alembic commands ###
